# Netlify Configuration for Fortune Wheel Game

[build]
  publish = "."
  
[[redirects]]
  from = "/"
  to = "/index_main.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/audio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*/png/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
