name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc -p tsconfig.json --noEmit

      - name: Build
        env:
          # Minimal env so Next.js build doesn't fail on missing variables
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: demo-anon-key
          SUPABASE_SERVICE_ROLE_KEY: demo-service-role-key
          OPENAI_API_KEY: demo-openai-key
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
